// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../models/db/pending_folder.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7975803295620667322),
      name: 'PendingFolderModel',
      lastPropertyId: const IdUid(3, 6599745506441588912),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5055437538870438322),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5067660810355604485),
            name: 'folderName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6599745506441588912),
            name: 'diaries',
            type: 30,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7975803295620667322),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    PendingFolderModel: EntityDefinition<PendingFolderModel>(
        model: _entities[0],
        toOneRelations: (PendingFolderModel object) => [],
        toManyRelations: (PendingFolderModel object) => {},
        getId: (PendingFolderModel object) => object.id,
        setId: (PendingFolderModel object, int id) {
          object.id = id;
        },
        objectToFB: (PendingFolderModel object, fb.Builder fbb) {
          final folderNameOffset = fbb.writeString(object.folderName);
          final diariesOffset = fbb.writeList(
              object.diaries.map(fbb.writeString).toList(growable: false));
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, folderNameOffset);
          fbb.addOffset(2, diariesOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = PendingFolderModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              folderName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              diaries: const fb.ListReader<String>(
                      fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGet(buffer, rootOffset, 8, []));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [PendingFolderModel] entity fields to define ObjectBox queries.
class PendingFolderModel_ {
  /// see [PendingFolderModel.id]
  static final id =
      QueryIntegerProperty<PendingFolderModel>(_entities[0].properties[0]);

  /// see [PendingFolderModel.folderName]
  static final folderName =
      QueryStringProperty<PendingFolderModel>(_entities[0].properties[1]);

  /// see [PendingFolderModel.diaries]
  static final diaries =
      QueryStringVectorProperty<PendingFolderModel>(_entities[0].properties[2]);
}
